#!/usr/bin/env bash

set -e
set -u
set -o pipefail

project_directory="$(dirname "${BASH_SOURCE[0]}")"
install_directory="${1:-$HOME/.local/bin}"

mkdir -p "$install_directory"

cat <<-EOF > "$install_directory/nbr"
	# this file is auto generated by a script, modifications will be overwritten
	${project_directory}/npm-bins-run.bash "\$@"
EOF

chmod +x "$install_directory/nbr"
